name: food_delivery
description: A Flutter Food Delivery application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.3
  google_sign_in: ^5.0.4
  provider: ^5.0.0
  splashscreen: ^1.3.5
  auto_size_text:
  font_awesome_flutter:
  google_fonts:
  intro_slider: ^2.4.3
  shared_preferences: ^2.0.6
  rxdart: ^0.27.1
  built_collection: ^5.0.0-nullsafety.0
  built_value: ^8.0.0-nullsafety.0
  flutter_inner_drawer: ^1.0.0+1
  cached_network_image: ^3.0.0
  flutter_cache_manager: 3.1.1

dev_dependencies:
  build_runner: ^1.11.0
  built_value_generator: ^8.0.0-nullsafety.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/